version: 0.2
phases:
  install:
    runtime-versions: null
    java: correctto17
  pre_build:
    commands:
      - echo "pre-build started"
      - pwd
      - ls -lrta
  build:
    commands:
      - echo Build started on 'date'
      - mvn package
      - echo Build completed on 'date'
  post_build:
    commands:
      - echo Deliver Artifact To Remove Tomcat Server 'date'
artifacts:
  files: -'**/*'
